[package]
name = "client"
version = "0.0.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
server = { path = "../server" }

bevy = { workspace = true }
bevy_renet = { workspace = true }
rand = { workspace = true }
ron = { workspace = true }
log = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
bevy_rapier3d = { workspace = true }
bincode = { workspace = true }

lazy_static = "1.5.0"
bevy_simple_text_input = "0.11"
bevy_atmosphere = "0.13"
bevy_water = "0.16"
bevy_panorbit_camera = "0.28"
bevy-inspector-egui = "0.31"
egui = "0.31"
bevy_image = "0.16.1"
iyes_progress = "0.14"
bevy_asset_loader = { version = "0.23", features = ["progress_tracking", "standard_dynamic_assets"] }
leafwing-input-manager = "0.17"

[lints]
workspace = true
