# Copilot Setup Steps
# This workflow is used by GitHub Copilot Coding Agent to set up the environment
# before running build commands. It installs system dependencies required by the
# Bevy game engine on Ubuntu.

name: "Copilot Setup Steps"

runs:
  using: "composite"
  steps:
    - name: Install system dependencies for Bevy
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          libasound2-dev \
          libudev-dev \
          libx11-dev \
          libxcursor-dev \
          libxi-dev \
          libxrandr-dev \
          libxinerama-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libssl-dev \
          libwayland-dev \
          libdbus-1-dev \
          cmake \
          libfreetype6-dev \
          libexpat1-dev \
          zlib1g-dev
