[package]
name = "server"
version = "0.0.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }

bevy = { workspace = true }
bevy_log = { workspace = true }
bevy_ecs = { workspace = true }
bevy_renet = { workspace = true }
noiz = { workspace = true }
rand = { workspace = true }
ron = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
bevy_rapier3d = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }

bevy_app = { version = "0.17", default-features=false }

ulid = "1.1.4"
futures-lite = "2.5"

# Define the library target
[lib]
name = "server"
path = "src/lib.rs"

# Define the binary target
[[bin]]
name = "server"
path = "src/main.rs"

[lints]
workspace = true
