[package]
name = "shared"
version = "0.0.0"
edition = "2021"

[dependencies]
derive-linear-schedule-set = { path = "../crates/derive-linear-schedule-set" }

bevy = { workspace = true }
bevy_log = { workspace = true }
bevy_ecs = { workspace = true }
bevy_renet = { workspace = true }
noiz = { workspace = true }
rand = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
bevy_rapier3d = { workspace = true }
bincode = { workspace = true }
itertools = { workspace = true }
packed-uints = { workspace = true }

lz4 = "1.28.1"
bevy_platform = "0.17"
nonempty = "0.12.0"
strum = { version = "0.27.2", features = ["strum_macros"] }
strum_macros = "0.27.2"

[lints]
workspace = true
